ASFLAGS_ADDITIONAL = -c -g -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_MICRO -DARDUINO_ARCH_AVR -D_RUNONTARGETHARDWARE_BUILD_ -D_ROTH_LEONARDO_ -DUSB_VID=0x2341 -DUSB_PID=0x8037 -DUSB_MANUFACTURER=\""Unknown\"" -DUSB_PRODUCT=\""Arduino Micro\""
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/PROGRA~3/MATLAB/SUPPOR~1/R2023b/toolbox/target/SUPPOR~1/ARDUIN~1/registry/..
STACK_SIZE = 64
